{% set name = "nigsp" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nigsp-{{ version }}.tar.gz
  sha256: f3f4b0d576124c7d5bd7b56df34f842e653e96877c5a87eeccb6d79693163b1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - nigsp = nigsp.workflow:_main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
  run:
    - duecredit
    - matplotlib-base >=3.1.1
    - nibabel
    - nilearn >=0.7.0
    - numpy
    - pymatreader
    - python >=3.8
    - scipy

test:
  imports:
    - nigsp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MIPLabCH/nigsp
  summary: A module for graph signal processing on neuroimaging data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smoia
    - mscheltienne
