{% set name = "nigsp" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nigsp-{{ version }}.tar.gz
  sha256: 320b303c1bf1c9873278b7a8f93b433c84ff14da0fb3425f6aa4732ab63f4e6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - nigsp = nigsp.workflow:_main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
  run:
    - duecredit
    - matplotlib-base >=3.1.1
    - nibabel
    - nilearn >=0.7.0
    - numpy
    - pymatreader
    - python >=3.8
    - scipy

test:
  imports:
    - nigsp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MIPLabCH/nigsp
  summary: A module for graph signal processing on neuroimaging data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smoia
    - mscheltienne
